FTX_API_KEY = 'YOUR_FTX_API_KEY';
FTX_SECRET = 'YOUR_FTX_SECRET';
FTX_SUBACCOUNT = 'YOUR_SUBACCOUNT_NAME';
FTX_END_POINT = 'https://ftx.com/api/';
BCH_THRESHOLD = 500;
MINIMUM_SIZE = 5;
UPDATE_OFFERING = 1;
MINIMUM_RATE = 0.049;
